services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: shiny run --reload --host 0.0.0.0 --port 8000 /crispr-shiny/app.py
    volumes:
      - ./outputs:/outputs

    develop:
      watch:
        - action: sync
          path: .
          target: /crispr-shiny     
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - node_modules/
        - action: rebuild
          path: requirements.txt

